insert into colombia.join_table (
`Client ID`,
`Client name 1`,
`SKU`,
`No. of SKU`,
`Sum of Ordered Quantity`,
`Sum of Delivery Quantity`,
`Sum of Return Quantity`,
`Rejected ID`,
`Sum of Net Cartons`,
`Sum of Net price delivered`,
`Sum of Net price after returns`,
`DC`,
`Channel`,
`Town`)
select
`Client ID`,
`Client name 1`,
`SKU`,
`No. of SKU`,
`Sum of Ordered Quantity`,
`Sum of Delivery Quantity`,
`Sum of Return Quantity`,
`Rejected ID`,
`Sum of Net Cartons`,
`Sum of Net price delivered`,
`Sum of Net price after returns`,
`DC`,
`Channel`,
`Town` from colombia.main_table left join colombia.clients using (`Client ID`) left join colombia.products using (`SKU`);
